services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 3s
      retries: 30

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg://app:app@db:5432/app
      SEED: "1"  # remove to run without demo data
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      retries: 3

  frontend:
    build: ./frontend
    environment:
      VITE_API_BASE_URL: http://backend:8000
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app         # optional live-reload dev mount
      - /app/node_modules

  db-init:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg://app:app@db:5432/app
      SEED: "1"
    depends_on:
      - db
    profiles: ["init"]            # run only when requested
    entrypoint: ["sh", "-c", "python -m app.init_db && python -m app.seed"]

volumes:
  db:
